### ISSUE TITLE
Daylight savings time?

### ISSUE THREAD

**Issue by Steph1116** [jake1164/Pico-RBG-Matrix-P3-64x32#2]
Sorry to have opened an issue. Resolved

**Comment by Steph1116** [comment]
I thought the issue was resolved. Not so.

Here is what's going on.

I go into the settings in the unit itself, I press the keys and set the time ahead one hour. I go back to the time by holding key2 in for a moment. The time is then displayed correctly. After a few minutes or so, the time reverts back to before I made the changes on its own. I also turned off the beep due to it being annoying, and that as well reverted back to being on.

So my issue is that it won't permanently save my changes. Ideas?

**Comment by jake1164** [comment]
Hi,

First a quesiton, when did the beep revert, was it after restarting the unit?

As for the time, there are a few issues here:

  1.  It needs to account for daylight savings. both of my clocks are wrong and my wife is gonna be complaining any time now.
  2.  When the time is manually adjusted the NTP synchronization needs to stop.
  3.  Guessing there needs to be a settings accessable way to turn NTP syncronization on / off.
  4.  There needs to be a way for the pico to save the user selected settings and read them on startup.

To work around the time you can turn off the NTP sync in the settings.toml file.


________________________________

**Comment by Steph1116** [comment]
The beep reverted back on at the same time the time went back to before I adjusted it. It happens roughly 6 minutes after I adjust the time.

**Comment by Steph1116** [comment]
I think I'll just need to do the timezone offset

**Comment by jake1164** [comment]
I do assume you are also using the https://github.com/jake1164/Pico-RGB-Matrix-Clock?
[https://opengraph.githubassets.com/f7a1a60bfb0b53642e37ea41f6b60d84232375c73b31d06b31ba9e072a0d041e/jake1164/Pico-RGB-Matrix-Clock]<https://github.com/jake1164/Pico-RGB-Matrix-Clock>
GitHub - jake1164/Pico-RGB-Matrix-Clock: An RGB Clock running on a Raspberry Pico W and a WaveShare Pico-RGB-Matrix-P3-64x32<https://github.com/jake1164/Pico-RGB-Matrix-Clock>
An RGB Clock running on a Raspberry Pico W and a WaveShare Pico-RGB-Matrix-P3-64x32 - GitHub - jake1164/Pico-RGB-Matrix-Clock: An RGB Clock running on a Raspberry Pico W and a WaveShare Pico-RGB-Ma...
github.com

________________________________

**Comment by Steph1116** [comment]
Fixed, adjusted the time zone offset to -4.

**Comment by jake1164** [comment]
Outstanding, I will look at the beep when I have a chance.

**Comment by Steph1116** [comment]
Perfect, thanks!
