### ISSUE TITLE
I thought the issue was resolved. Not so.

### ISSUE THREAD

**Issue by Steph1116** [jake1164/Pico-RBG-Matrix-P3-64x32#3]
I thought the issue was resolved. Not so.

Here is what's going on.

I go into the settings in the unit itself, I press the keys and set the time ahead one hour. I go back to the time by holding key2 in for a moment. The time is then displayed correctly. After a few minutes or so, the time reverts back to before I made the changes on its own. I also turned off the beep due to it being annoying, and that as well reverted back to being on.

So my issue is that it won't permanently save my changes. Ideas?

_Originally posted by @Steph1116 in https://github.com/jake1164/Pico-RBG-Matrix-P3-64x32/issues/2#issuecomment-1465206474_

**Comment by jake1164** [comment]
Are you still seeing this issue with the latest version and if its with the Clock can we open the issue over there?

**Comment by Steph1116** [comment]
After I changed the hour back in the code itself, I had no issues. I didn't use any buttons for the fix so I can't say for sure that it's resolved unless I recreate what I originally did to try and fix the time. Once the UTC offset was adjusted, I put my clock back across the room and all was good.

**Comment by jake1164** [comment]
Did you rename the _boot.py file to boot.py?  that is required to save settings between reboots.

(also means you can update the code without holding the bottom button)
________________________________

**Comment by Steph1116** [comment]
I believe so. That was a bit ago so I can't quite remember what I did. But everything worked afterwards so I did something right lol.
